### ISSUE TITLE
Code lint checking feature

### ISSUE THREAD

**Issue by tvytlx** [laixintao/git-ext#15]
run code linter(like flake8..) only on your **modified files or staged files**

e.g. `git check-lint flake8`

Could you implement this?

**Comment by laixintao** [comment]
Yes, we can use git find diff files then use tools check lint. I will work on this.

But you may want git's [pre-commit hook](https://git-scm.com/book/zh/v2/%E8%87%AA%E5%AE%9A%E4%B9%89-Git-Git-%E9%92%A9%E5%AD%90), like:

```
#!/usr/bin/python

import sys
from flake8.run import git_hook

COMPLEXITY = 12
STRICT = True

if __name__ == '__main__':
    sys.exit(git_hook(complexity=COMPLEXITY, strict=STRICT))
```

**Comment by laixintao** [comment]
Oh, just found that flake support git hook:

`flake8 --install-hook git`

**Comment by tvytlx** [comment]
may don't need this now, so just close it or whatever 😂

**Comment by laixintao** [comment]
Still I think git commit hook is better.
